# Generated by Django 5.0.4 on 2024-05-03 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='year',
            field=models.IntegerField(),
        ),
    ]
