# Generated by Django 5.0.4 on 2024-05-03 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos_app', '0002_alter_vehiculo_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chofer',
            old_name='Vehiculo_id',
            new_name='vehiculo_id',
        ),
        migrations.RenameField(
            model_name='registrocontabilidad',
            old_name='Vehiculo_id',
            new_name='vehiculo_id',
        ),
    ]
